"use server";

import { auth } from "@/auth";
import prisma from "@/lib/prisma";
import { revalidatePath } from "next/cache";

export async function createCircle(formData: FormData) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const name = formData.get("name") as string;
  const description = formData.get("description") as string;
  // inviteCode is automatically generated by default in schema

  const circle = await prisma.circle.create({
    data: {
      name,
      description,
      ownerId: session.user.id,
      members: {
        create: {
          userId: session.user.id,
          role: "OWNER",
        },
      },
    },
  });

  revalidatePath("/");
  return circle;
}

export async function getMyCircles() {
  const session = await auth();
  if (!session?.user?.id) return [];

  return await prisma.circle.findMany({
    where: {
      members: {
        some: {
          userId: session.user.id,
        },
      },
    },
    include: {
      _count: {
        select: { members: true },
      },
      owner: true,
    },
  });
}

export async function getCircle(id: string) {
  const session = await auth();
  if (!session?.user?.id) return null;

  const circle = await prisma.circle.findUnique({
    where: { id },
    include: {
      members: {
        include: {
          user: true,
        },
      },
      invites: {
        orderBy: { eventDate: "desc" },
        include: {
          _count: {
            select: { rsvps: true },
          },
        },
      },
      owner: true,
    },
  });

  if (!circle) return null;

  // Authorization check: User must be a member
  const isMember = circle.members.some(
    (member) => member.userId === session.user.id,
  );

  if (!isMember) return null;

  return circle;
}

export async function regenerateInviteCode(circleId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle || circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized");
  }

  const { nanoid } = await import("nanoid");
  const newCode = nanoid(10);

  await prisma.circle.update({
    where: { id: circleId },
    data: { inviteCode: newCode },
  });

  revalidatePath(`/circle/${circleId}`);
  return newCode;
}

export async function joinCircleByCode(code: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  // First check if it's a limited invite link
  const limitedLink = await prisma.circleInviteLink.findUnique({
    where: { code },
    include: { circle: { include: { members: true } } },
  });

  if (limitedLink) {
    // Check if usage limit is reached
    if (limitedLink.usedCount >= limitedLink.maxUses) {
      throw new Error("This invite link has reached its usage limit");
    }

    const isMember = limitedLink.circle.members.some(
      (member) => member.userId === session.user.id,
    );

    if (isMember) {
      return {
        success: true,
        circleId: limitedLink.circleId,
        alreadyMember: true,
      };
    }

    // Add member with ACTIVE status and increment usage count
    await prisma.$transaction([
      prisma.circleMember.create({
        data: {
          userId: session.user.id,
          circleId: limitedLink.circleId,
          role: "MEMBER",
          status: "ACTIVE",
        },
      }),
      prisma.circleInviteLink.update({
        where: { id: limitedLink.id },
        data: { usedCount: { increment: 1 } },
      }),
    ]);

    revalidatePath(`/circle/${limitedLink.circleId}`);
    revalidatePath("/");
    return { success: true, circleId: limitedLink.circleId };
  }

  // Check general invite code
  const circle = await prisma.circle.findUnique({
    where: { inviteCode: code },
    include: { members: true },
  });

  if (!circle) throw new Error("Invalid invite code");

  // Check if general invite link is enabled
  if (!circle.isInviteLinkEnabled) {
    throw new Error("This invite link has been disabled");
  }

  const isMember = circle.members.some(
    (member) => member.userId === session.user.id,
  );

  if (isMember) {
    return { success: true, circleId: circle.id, alreadyMember: true };
  }

  // Add member with PENDING status for general invite link
  await prisma.circleMember.create({
    data: {
      userId: session.user.id,
      circleId: circle.id,
      role: "MEMBER",
      status: "PENDING",
    },
  });

  revalidatePath(`/circle/${circle.id}`);
  revalidatePath("/");
  return { success: true, circleId: circle.id };
}

export async function getCircleByInviteCode(code: string) {
  // First check limited invite link
  const limitedLink = await prisma.circleInviteLink.findUnique({
    where: { code },
    include: {
      circle: {
        include: {
          owner: true,
          _count: {
            select: { members: true },
          },
        },
      },
    },
  });

  if (limitedLink) {
    // Check if link is still valid
    if (limitedLink.usedCount >= limitedLink.maxUses) {
      return null;
    }
    return limitedLink.circle;
  }

  // Check general invite code
  const circle = await prisma.circle.findUnique({
    where: { inviteCode: code },
    include: {
      owner: true,
      _count: {
        select: { members: true },
      },
    },
  });
  return circle;
}

export async function deleteCircle(circleId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle) throw new Error("Circle not found");

  if (circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized: Only the owner can delete this circle");
  }

  await prisma.circle.delete({
    where: { id: circleId },
  });

  revalidatePath("/");
  return { success: true };
}

export async function createLimitedInviteLink(
  circleId: string,
  maxUses: number,
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle || circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized");
  }

  const { nanoid } = await import("nanoid");
  const code = nanoid(10);

  const inviteLink = await prisma.circleInviteLink.create({
    data: {
      circleId,
      code,
      maxUses,
      creatorId: session.user.id,
    },
  });

  revalidatePath(`/circle/${circleId}`);
  return inviteLink;
}

export async function getLimitedInviteLinks(circleId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle || circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized");
  }

  return await prisma.circleInviteLink.findMany({
    where: { circleId },
    orderBy: { createdAt: "desc" },
  });
}

export async function revokeLimitedInviteLink(linkId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const link = await prisma.circleInviteLink.findUnique({
    where: { id: linkId },
    include: { circle: true },
  });

  if (!link || link.circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized");
  }

  await prisma.circleInviteLink.delete({
    where: { id: linkId },
  });

  revalidatePath(`/circle/${link.circleId}`);
  return { success: true };
}

export async function updateCircleSettings(
  circleId: string,
  settings: { isInviteLinkEnabled?: boolean },
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Unauthorized");

  const circle = await prisma.circle.findUnique({
    where: { id: circleId },
  });

  if (!circle || circle.ownerId !== session.user.id) {
    throw new Error("Unauthorized");
  }

  const updated = await prisma.circle.update({
    where: { id: circleId },
    data: settings,
  });

  revalidatePath(`/circle/${circleId}`);
  return updated;
}
